<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    public function run()
    {

        $cities = [

   [

    ['en' => 'Muthanna', 'ar' => 'المثنى'],
    ['en' => 'Al-Qadisiyyah', 'ar' => 'القادسية'],
    ['en' => 'Sulaymaniyah', 'ar' => 'السليمانية'],
    ['en' => 'Erbil', 'ar' => 'أربيل'],
    ['en' => 'Anbar', 'ar' => 'الأنبار'],
    ['en' => 'Babil', 'ar' => 'بابل'],
    ['en' => 'Baghdad', 'ar' => 'بغداد'],
    ['en' => 'Basra', 'ar' => 'البصرة'],
    ['en' => 'Duhok', 'ar' => 'دهوك'],
    ['en' => 'Dhi Qar', 'ar' => 'ذي قار'],
    ['en' => 'Diyala', 'ar' => 'ديالى'],
    ['en' => 'Salah ad-Din', 'ar' => 'صلاح الدين'],
    ['en' => 'Halabja', 'ar' => 'حلبجة'],
    ['en' => 'Karbala', 'ar' => 'كربلاء'],
    ['en' => 'Kirkuk', 'ar' => 'كركوك'],
    ['en' => 'Maysan', 'ar' => 'ميسان'],
    ['en' => 'Najaf', 'ar' => 'النجف'],
    ['en' => 'Nineveh', 'ar' => 'نينوى'],
    ['en' => 'Wasit', 'ar' => 'واسط']
]

    // ['en' => 'Aleppo', 'ar' => 'حلب'],
    // ['en' => 'Raqqa', 'ar' => 'الرقة'],
    // ['en' => 'As-Suwayda', 'ar' => 'السويداء'],
    // ['en' => 'Damascus', 'ar' => 'دمشق'],
    // ['en' => 'Daraa', 'ar' => 'درعا'],
    // ['en' => 'Deir ez-Zor', 'ar' => 'دير الزور'],
    // ['en' => 'Hama', 'ar' => 'حماة'],
    // ['en' => 'Al-Hasakah', 'ar' => 'الحسكة'],
    // ['en' => 'Homs', 'ar' => 'حمص'],
    // ['en' => 'Idlib', 'ar' => 'إدلب'],
    // ['en' => 'Latakia', 'ar' => 'اللاذقية'],
    // ['en' => 'Quneitra', 'ar' => 'القنيطرة'],
    // ['en' => 'Rif Dimashq', 'ar' => 'ريف دمشق'],
    // ['en' => 'Tartus', 'ar' => 'طرطوس']



            // ['en' => 'Baghdad (Baghdad)', 'ar' => 'بغداد (بغداد)'],
            // ['en' => 'Baghdad (Al-Karkh)', 'ar' => 'بغداد (الكرخ)'],
            // ['en' => 'Baghdad (Al-Rusafa)', 'ar' => 'بغداد (الرصافة)'],
            // ['en' => 'Baghdad (Al-Fadhil)', 'ar' => 'بغداد (الفضل)'],
            // ['en' => 'Baghdad (Al-Sadriya)', 'ar' => 'بغداد (الصدرية)'],
            // ['en' => 'Baghdad (Bab Al-Sheikh)', 'ar' => 'بغداد (باب الشيخ)'],
            // ['en' => 'Baghdad (Al-Athefiya)', 'ar' => 'بغداد (العطيفية)'],
            // ['en' => 'Baghdad (Al-Kadhimiya)', 'ar' => 'بغداد (الكاظمية)'],
            // ['en' => 'Baghdad (Al-Adhamiya)', 'ar' => 'بغداد (الأعظمية)'],
            // ['en' => 'Baghdad (Al-Shaab)', 'ar' => 'بغداد (الشعب)'],
            // ['en' => 'Baghdad (Al-Karada)', 'ar' => 'بغداد (الكرادة)'],
            // ['en' => 'Baghdad (Al-Mansour)', 'ar' => 'بغداد (المنصور)'],
            // ['en' => 'Baghdad (Al-Qadisiyah)', 'ar' => 'بغداد (القادسية)'],
            // ['en' => 'Baghdad (Al-Maamoun)', 'ar' => 'بغداد (المأمون)'],
            // ['en' => 'Baghdad (Al-Dora)', 'ar' => 'بغداد (الدورة)'],
            // ['en' => 'Baghdad (Al-Ghazaliya)', 'ar' => 'بغداد (الغزالية)'],
            // ['en' => 'Baghdad (Al-Jadriya)', 'ar' => 'بغداد (الجادرية)'],
            // ['en' => 'Baghdad (Al-Zaafaraniya)', 'ar' => 'بغداد (الزعفرانية)'],
            // ['en' => 'Baghdad (Al-Madaen)', 'ar' => 'بغداد (المدائن)'],
            // ['en' => 'Baghdad (Abu Ghraib)', 'ar' => 'بغداد (أبو غريب)'],
            // ['en' => 'Baghdad (Al-Shula)', 'ar' => 'بغداد (الشعلة)'],
            // ['en' => 'Baghdad (Al-Hurriya)', 'ar' => 'بغداد (الحرية)'],
            // ['en' => 'Baghdad (Al-Taji)', 'ar' => 'بغداد (التاجي)'],
            // ['en' => 'Baghdad (Al-Tarmiyah)', 'ar' => 'بغداد (الطارمية)'],
            // ['en' => 'Baghdad (Al-Mahmoudiya)', 'ar' => 'بغداد (المحمودية)'],




            // ['en' => 'Baghdad (Al-Karradah)', 'ar' => 'بغداد (الكرادة)'],
            // ['en' => 'Baghdad (Al-Saydiya)', 'ar' => 'بغداد (السيدية)'],
            // ['en' => 'Baghdad (Al-Yarmouk)', 'ar' => 'بغداد (اليرموك)'],
            // ['en' => 'Baghdad (Al-Bayaa)', 'ar' => 'بغداد (البياع)'],
            // ['en' => 'Baghdad (Al-Hurriya City)', 'ar' => 'بغداد (مدينة الحرية)'],
            // ['en' => 'Baghdad (Al-Shuala)', 'ar' => 'بغداد (الشعلة)'],
            // ['en' => 'Baghdad (Al-Amel)', 'ar' => 'بغداد (العامل)'],
            // ['en' => 'Baghdad (Al-Jihad)', 'ar' => 'بغداد (الجهاد)'],
            // ['en' => 'Baghdad (Al-Sayyidiyah)', 'ar' => 'بغداد (السيدية)'],
            // ['en' => 'Baghdad (Al-Khadraa)', 'ar' => 'بغداد (الخضراء)'],
            // ['en' => 'Baghdad (Al-Rasheed)', 'ar' => 'بغداد (الرشيد)'],
            // ['en' => 'Baghdad (Al-Dawra)', 'ar' => 'بغداد (الدورة)'],
            // ['en' => 'Baghdad (Al-Salam)', 'ar' => 'بغداد (السلام)'],
            // ['en' => 'Baghdad (Al-Qahira)', 'ar' => 'بغداد (القاهرة)'],
            // ['en' => 'Baghdad (Al-Waziriya)', 'ar' => 'بغداد (الوزيرية)'],
            // ['en' => 'Baghdad (Al-Utafiyya)', 'ar' => 'بغداد (العطيفية)'],
            // ['en' => 'Baghdad (Al-Sa adoon)', 'ar' => 'بغداد (السعدون)'],
            // ['en' => 'Baghdad (Al-Salhiya)', 'ar' => 'بغداد (الصالحية)'],
            // ['en' => 'Baghdad (Al-Bataween)', 'ar' => 'بغداد (البتاوين)'],
            // ['en' => 'Baghdad (Al-Mansour)', 'ar' => 'بغداد (المنصور)'],
            // ['en' => 'Baghdad (Al-Adel)', 'ar' => 'بغداد (العادل)'],
            // ['en' => 'Baghdad (Al-Harthiya)', 'ar' => 'بغداد (الحارثية)'],
            // ['en' => 'Baghdad (Al-Zayouna)', 'ar' => 'بغداد (الزيونة)'],
            // ['en' => 'Baghdad (Al-Muthanna)', 'ar' => 'بغداد (المثنى)'],
            // ['en' => 'Baghdad (Al-Qadisiyah)', 'ar' => 'بغداد (القادسية)'],
            // ['en' => 'Baghdad (Al-Maamoun)', 'ar' => 'بغداد (المأمون)'],
            // ['en' => 'Baghdad (Al-Jamia)', 'ar' => 'بغداد (الجامعة)'],
            // ['en' => 'Baghdad (Al-Saadoon)', 'ar' => 'بغداد (السعدون)'],
            // ['en' => 'Baghdad (Al-Salhiya)', 'ar' => 'بغداد (الصالحية)'],
            // ['en' => 'Baghdad (Al-Bataween)', 'ar' => 'بغداد (البتاوين)'],
            // ['en' => 'Baghdad (Al-Mansour)', 'ar' => 'بغداد (المنصور)'],
            // ['en' => 'Baghdad (Al-Adel)', 'ar' => 'بغداد (العادل)'],
            // ['en' => 'Baghdad (Al-Harthiya)', 'ar' => 'بغداد (الحارثية)'],
            // ['en' => 'Baghdad (Al-Zayouna)', 'ar' => 'بغداد (الزيونة)'],
            // ['en' => 'Baghdad (Al-Muthanna)', 'ar' => 'بغداد (المثنى)'],
            // ['en' => 'Baghdad (Al-Qadisiyah)', 'ar' => 'بغداد (القادسية)'],
            // ['en' => 'Baghdad (Al-Maamoun)', 'ar' => 'بغداد (المأمون)'],
            // ['en' => 'Baghdad (Al-Jamia)', 'ar' => 'بغداد (الجامعة)'],


            // ['en' => 'Basra (Basra)', 'ar' => 'البصرة (البصرة)'],
            // ['en' => 'Basra (Shatt Al-Arab)', 'ar' => 'البصرة (شط العرب)'],
            // ['en' => 'Basra (Abu Al-Khasib)', 'ar' => 'البصرة (أبو الخصيب)'],
            // ['en' => 'Basra (Al-Zubair)', 'ar' => 'البصرة (الزبير)'],
            // ['en' => 'Basra (Al-Qurna)', 'ar' => 'البصرة (القرنة)'],
            // ['en' => 'Basra (Umm Qasr)', 'ar' => 'البصرة (أم قصر)'],
            // ['en' => 'Basra (Al-Faw)', 'ar' => 'البصرة (الفاو)'],
            // ['en' => 'Basra (Al-Midaina)', 'ar' => 'البصرة (المدينة)'],
            // ['en' => 'Basra (Al-Hartha)', 'ar' => 'البصرة (الهارثة)'],
            // ['en' => 'Basra (Al-Tanuma)', 'ar' => 'البصرة (التنومة)'],
            // ['en' => 'Basra (Al-Siba)', 'ar' => 'البصرة (السيبة)'],
            // ['en' => 'Basra (Al-Ashar)', 'ar' => 'البصرة (العشار)'],
            // ['en' => 'Basra (Al-Maqal)', 'ar' => 'البصرة (المقلاع)'],
            // ['en' => 'Basra (Al-Baradiyah)', 'ar' => 'البصرة (البراضعية)'],
            // ['en' => 'Basra (Al-Jubaila)', 'ar' => 'البصرة (الجبيليات)'],
            // ['en' => 'Basra (Al-Dayr)', 'ar' => 'البصرة (الدير)'],
            // ['en' => 'Basra (Al-Qibla)', 'ar' => 'البصرة (القبلة)'],
            // ['en' => 'Basra (Al-Madinah)', 'ar' => 'البصرة (المدينة)'],
            // ['en' => 'Basra (Al-Seeba)', 'ar' => 'البصرة (السيبة)'],
            // ['en' => 'Basra (Al-Tanuma)', 'ar' => 'البصرة (التنومة)'],
            // ['en' => 'Basra (Al-Hartha)', 'ar' => 'البصرة (الهارثة)'],
            // ['en' => 'Basra (Abu Al-Khasib)', 'ar' => 'قضاء أبو الخصيب'],
            // ['en' => 'Basra (Shafi Subdistrict)', 'ar' => 'ناحية الشافي'],
            // ['en' => 'Basra (Sharsh Subdistrict)', 'ar' => 'ناحية الشرش'],
            // ['en' => 'Basra (Salhiya Subdistrict)', 'ar' => 'ناحية الصالحية'],
            // ['en' => 'Basra (Fayha Subdistrict)', 'ar' => 'ناحية الفيحاء'],
            // ['en' => 'Basra (Khor Al-Zubair)', 'ar' => 'ناحية خور الزبير'],
            // ['en' => 'Basra (Martyr Izz Al-Din Salim District)', 'ar' => 'قضاء الشهيد عز الدين سليم'],
            // ['en' => 'Basra (Seeba District)', 'ar' => 'ناحية السيبة'],
            // ['en' => 'Basra (Narjis City)', 'ar' => 'مدينة النرجس'],
            // ['en' => 'Basra (Bahar Subdistrict)', 'ar' => 'ناحية البحار'],
            // ['en' => 'Basra (Imam Al-Qaim Subdistrict)', 'ar' => 'ناحية الإمام القائم'],
            // ['en' => 'Basra (Imam Al-Sadiq District)', 'ar' => 'قضاء الامام الصادق'],
            // ['en' => 'Basra (Nashwa Subdistrict)', 'ar' => 'ناحية النشوة'],
            // ['en' => 'Basra (Kibasi)', 'ar' => 'الكباسي'],
            // ['en' => 'Basra (Um Qasr)', 'ar' => 'أم قصر'],
            // ['en' => 'Basra (Fao District)', 'ar' => 'قضاء الفاو'],
            // ['en' => 'Basra (Safwan)', 'ar' => 'سفوان'],
            // ['en' => 'Basra (Zubair)', 'ar' => 'الزبير'],
            // ['en' => 'Basra (Qurna)', 'ar' => 'القرنة'],
            // ['en' => 'Basra (Medina)', 'ar' => 'المدينة'],
            // ['en' => 'Basra (Huwayr)', 'ar' => 'الهوير'],
            // ['en' => 'Basra (Shuaiba)', 'ar' => 'الشعيبة'],
            // ['en' => 'Basra (Rumeila)', 'ar' => 'الرميلة'],
            // ['en' => 'Basra (Amal City)', 'ar' => 'مدينة الأمل'],
            // ['en' => 'Basra (Manawi Basha)', 'ar' => 'مناوي باشا'],
            // ['en' => 'Basra (Manawi Lejum)', 'ar' => 'مناوي لجم'],
            // ['en' => 'Basra (Kafa’at)', 'ar' => 'الكفاءات'],
            // ['en' => 'Basra (Khudra)', 'ar' => 'الخضراء'],
            // ['en' => 'Basra (Al-Asma’i Old)', 'ar' => 'الأصمعي القديم'],
            // ['en' => 'Basra (Al-Asma’i New)', 'ar' => 'الأصمعي الجديد'],
            // ['en' => 'Basra (Gulf District)', 'ar' => 'ناحية الخليج العربي'],
            // ['en' => 'Basra (Al-Abbasiya Area)', 'ar' => 'منطقة العباسية'],
            // ['en' => 'Basra (Hakimiya)', 'ar' => 'الحكيمية'],
            // ['en' => 'Basra (Tawisa)', 'ar' => 'الطويسة'],
            // ['en' => 'Basra (Ma’qal District)', 'ar' => 'ناحية المعقل'],
            // ['en' => 'Basra (Karma Ali)', 'ar' => 'كرمة علي'],
            // ['en' => 'Basra (Abu Flous Port)', 'ar' => 'ناحية الميناء (أبو فلوس)'],
            // ['en' => 'Basra (Dair)', 'ar' => 'الدير (العراق)'],
            // ['en' => 'Basra (Abu Basir District)', 'ar' => 'ناحية أبو بصير'],
            // ['en' => 'Basra (Um Al-Shuyoukh Subdistrict)', 'ar' => 'ناحية أم الشيوخ'],
            // ['en' => 'Basra (Khas Subdistrict)', 'ar' => 'ناحية الخاص'],
            // ['en' => 'Basra (Abu Mughira)', 'ar' => 'أبو مغيرة'],
            // ['en' => 'Basra (Saraji)', 'ar' => 'السراجي'],
            // ['en' => 'Basra (Muhaijiran)', 'ar' => 'مهيجران'],
            // ['en' => 'Basra (Hamdan)', 'ar' => 'حمدان'],
            // ['en' => 'Basra (Muhaila)', 'ar' => 'محيلة'],
            // ['en' => 'Basra (Sankar)', 'ar' => 'الصنكر'],
            // ['en' => 'Basra (Nahr Khuz)', 'ar' => 'نهرخوز'],
            // ['en' => 'Basra (Jaikur)', 'ar' => 'جيكور'],




            // ['en' => 'Nineveh (Mosul)', 'ar' => 'نينوى (الموصل)'],
            // ['en' => 'Nineveh (Tal Afar)', 'ar' => 'نينوى (تلعفر)'],
            // ['en' => 'Nineveh (Sinjar)', 'ar' => 'نينوى (سنجار)'],
            // ['en' => 'Nineveh (Al-Hamdaniya)', 'ar' => 'نينوى (الحمدانية)'],
            // ['en' => 'Nineveh (Al-Baaj)', 'ar' => 'نينوى (البعاج)'],
            // ['en' => 'Nineveh (Al-Qayyarah)', 'ar' => 'نينوى (القيارة)'],
            // ['en' => 'Nineveh (Al-Shura)', 'ar' => 'نينوى (الشورة)'],
            // ['en' => 'Nineveh (Hammam Al-Alil)', 'ar' => 'نينوى (حمام العليل)'],
            // ['en' => 'Nineveh (Taharawa)', 'ar' => 'نينوى (طهراوة)'],
            // ['en' => 'Nineveh (Bashiqa)', 'ar' => 'نينوى (بعشيقة)'],
            // ['en' => 'Nineveh (Al-Mahlabiya)', 'ar' => 'نينوى (المحلبية)'],
            // ['en' => 'Nineveh (Hamidat)', 'ar' => 'نينوى (حميدات)'],
            // ['en' => 'Nineveh (Ayadiyah)', 'ar' => 'نينوى (العياضية)'],
            // ['en' => 'Nineveh (Rabi’ah)', 'ar' => 'نينوى (ربيعة)'],
            // ['en' => 'Nineveh (Zummar)', 'ar' => 'نينوى (زمار)'],
            // ['en' => 'Nineveh (Al-Shamal or Snuny)', 'ar' => 'نينوى (الشمال أو سنوني)'],
            // ['en' => 'Nineveh (Al-Qairawan)', 'ar' => 'نينوى (القيروان)'],
            // ['en' => 'Nineveh (Al-Qahtaniya)', 'ar' => 'نينوى (القحطانية)'],
            // ['en' => 'Nineveh (Al-Hadar)', 'ar' => 'نينوى (الحضر)'],
            // ['en' => 'Nineveh (Tal Abta)', 'ar' => 'نينوى (تل عبطة)'],
            // ['en' => 'Nineveh (Bartella)', 'ar' => 'نينوى (برطلة)'],
            // ['en' => 'Nineveh (Telkaif)', 'ar' => 'نينوى (تلكيف)'],
            // ['en' => 'Nineveh (Wana)', 'ar' => 'نينوى (وانة)'],
            // ['en' => 'Nineveh (Alqosh)', 'ar' => 'نينوى (القوش)'],
            // ['en' => 'Nineveh (Fayda)', 'ar' => 'نينوى (فايدة)'],
            // ['en' => 'Nineveh (Sheikhan)', 'ar' => 'نينوى (الشيخان)'],
            // ['en' => 'Nineveh (Makhmur)', 'ar' => 'نينوى (مخمور)'],
            // ['en' => 'Nineveh (Al-Kuwayr)', 'ar' => 'نينوى (الكوير)'],
            // ['en' => 'Nineveh (Qaraq)', 'ar' => 'نينوى (قراج)'],
            // ['en' => 'Nineveh (Tel Safok)', 'ar' => 'نينوى (تل صفوك)'],
            // ['en' => 'Nineveh (Wardiya)', 'ar' => 'نينوى (وردية)'],
            // ['en' => 'Nineveh (Saadiyah)', 'ar' => 'نينوى (السعدية)'],
            // ['en' => 'Nineveh (Nimrud)', 'ar' => 'نينوى (النمرود)'],
            // ['en' => 'Nineveh (Tel Makhdhram)', 'ar' => 'نينوى (تل المخضرم)'],
            // ['en' => 'Nineveh (Adan)', 'ar' => 'نينوى (عدان)'],
            // ['en' => 'Nineveh (Tel Ghazal)', 'ar' => 'نينوى (تل غزال)'],
            // ['en' => 'Nineveh (Muwailiha)', 'ar' => 'نينوى (مويلحة)'],
            // ['en' => 'Nineveh (Al-Rawi)', 'ar' => 'نينوى (الراوي)'],
            // ['en' => 'Nineveh (Tel Samir)', 'ar' => 'نينوى (تل سمير)'],
            // ['en' => 'Nineveh (Tel Sayf)', 'ar' => 'نينوى (تل سيف)'],
            // ['en' => 'Nineveh (Rummana City)', 'ar' => 'نينوى (مدينة الرمانة)'],
            // ['en' => 'Nineveh (Tel Sheikh)', 'ar' => 'نينوى (تل الشيخ)'],
            // ['en' => 'Nineveh (Kurdiyan)', 'ar' => 'نينوى (كرديان)'],
            // ['en' => 'Nineveh (Dawser City)', 'ar' => 'نينوى (مدينة دوسر)'],
            // ['en' => 'Nineveh (Surja City)', 'ar' => 'نينوى (مدينة السورجة)'],
            // ['en' => 'Nineveh (Kalna City)', 'ar' => 'نينوى (مدينة كالنة)'],
            // ['en' => 'Nineveh (Irawan City)', 'ar' => 'نينوى (مدينة ايروان)'],
            // ['en' => 'Nineveh (Kosa City)', 'ar' => 'نينوى (مدينة كوسة)'],
            // ['en' => 'Nineveh (Harrar City)', 'ar' => 'نينوى (مدينة هرار)'],
            // ['en' => 'Nineveh (Alka City)', 'ar' => 'نينوى (مدينة علكه)'],
            // ['en' => 'Nineveh (Ashkafnah City)', 'ar' => 'نينوى (مدينة اشكفنه)'],
            // ['en' => 'Nineveh (Bakhma City)', 'ar' => 'نينوى (مدينة بخمة)'],





            // ['en' => 'Erbil (Erbil)', 'ar' => 'أربيل (أربيل)'],
            // ['en' => 'Erbil (Ankawa)', 'ar' => 'أربيل (عنكاوا)'],
            // ['en' => 'Erbil (Koya)', 'ar' => 'أربيل (كويه)'],
            // ['en' => 'Erbil (Shaqlawa)', 'ar' => 'أربيل (شقلاوة)'],
            // ['en' => 'Erbil (Soran)', 'ar' => 'أربيل (سوران)'],
            // ['en' => 'Erbil (Rawanduz)', 'ar' => 'أربيل (رواندوز)'],
            // ['en' => 'Erbil (Rayat)', 'ar' => 'أربيل (رايات)'],
            // ['en' => 'Erbil (Kasanazan Subdistrict)', 'ar' => 'أربيل (ناحية كسنزان)'],
            // ['en' => 'Erbil (Al-Kalk Subdistrict)', 'ar' => 'أربيل (ناحية الكلك)'],
            // ['en' => 'Erbil (Rawanduz City)', 'ar' => 'أربيل (مدينة رواندوز)'],
            // ['en' => 'Erbil (Shaqlawa)', 'ar' => 'أربيل (شقلاوة)'],
            // ['en' => 'Erbil (Salah Al-Din)', 'ar' => 'أربيل (صلاح الدين)'],
            // ['en' => 'Erbil (Koy Sanjaq)', 'ar' => 'أربيل (كوي سنجق)'],
            // ['en' => 'Erbil (Rawanduz)', 'ar' => 'أربيل (رواندوز)'],
            // ['en' => 'Erbil (Ankawa)', 'ar' => 'أربيل (عينكاوة)'],
            // ['en' => 'Erbil (Soran)', 'ar' => 'أربيل (سوران)'],
            // ['en' => 'Erbil (Mergasor)', 'ar' => 'أربيل (ميركسور)'],
            // ['en' => 'Erbil (Goman)', 'ar' => 'أربيل (جومان)'],
            // ['en' => 'Erbil (Khabat)', 'ar' => 'أربيل (خبات)'],
            // ['en' => 'Erbil (Binaslawa)', 'ar' => 'أربيل (بنصلاوة)'],
            // ['en' => 'Erbil (Shakran)', 'ar' => 'أربيل (شركران)'],
            // ['en' => 'Erbil (Kharaba)', 'ar' => 'أربيل (خرابه)'],
            // ['en' => 'Erbil (Hasarok)', 'ar' => 'أربيل (حصاروك)'],
            // ['en' => 'Erbil (Kum Tapa)', 'ar' => 'أربيل (كوم تبه)'],
            // ['en' => 'Erbil (Khrisani)', 'ar' => 'أربيل (خريساني)'],
            // ['en' => 'Erbil (Al-Kuwayr)', 'ar' => 'أربيل (الكوير)'],
            // ['en' => 'Erbil (Hanjruk)', 'ar' => 'أربيل (هنجروك)'],
            // ['en' => 'Erbil (Biroman)', 'ar' => 'أربيل (بيرومان)'],
            // ['en' => 'Erbil (Kurdarak)', 'ar' => 'أربيل (كردارك)'],
            // ['en' => 'Erbil (Harier)', 'ar' => 'أربيل (حرير)'],
            // ['en' => 'Erbil (Khalifan)', 'ar' => 'أربيل (خليفان)'],
            // ['en' => 'Erbil (Bonawi)', 'ar' => 'أربيل (بوناوي)'],
            // ['en' => 'Erbil (Gurga)', 'ar' => 'أربيل (جورحه)'],
            // ['en' => 'Erbil (Kani Rash)', 'ar' => 'أربيل (كاني رش)'],
            // ['en' => 'Erbil (Kikila)', 'ar' => 'أربيل (كيكله)'],
            // ['en' => 'Erbil (Talan)', 'ar' => 'أربيل (طالبان)'],
            // ['en' => 'Erbil (Taq Taq)', 'ar' => 'أربيل (طق طق)'],
            // ['en' => 'Erbil (Bayazok)', 'ar' => 'أربيل (بيازوك)'],
            // ['en' => 'Erbil (Wilda)', 'ar' => 'أربيل (اولده)'],
            // ['en' => 'Erbil (Hajji Omeran)', 'ar' => 'أربيل (حاج عمران)'],
            // ['en' => 'Erbil (Goman)', 'ar' => 'أربيل (جومان)'],
            // ['en' => 'Erbil (Rust)', 'ar' => 'أربيل (روست)'],
            // ['en' => 'Erbil (Birkim)', 'ar' => 'أربيل (بيركم)'],
            // ['en' => 'Erbil (Diana)', 'ar' => 'أربيل (ديانا)'],
            // ['en' => 'Erbil (Walza)', 'ar' => 'أربيل (ولزه)'],
            // ['en' => 'Erbil (Barzan)', 'ar' => 'أربيل (بارزان)'],
            // ['en' => 'Erbil (Shirwan Mazin)', 'ar' => 'أربيل (شيروان مازن)'],
            // ['en' => 'Erbil (Bakhshan)', 'ar' => 'أربيل (بخشائن)'],
            // ['en' => 'Erbil (Kabartu)', 'ar' => 'أربيل (كبركل)'],
            // ['en' => 'Erbil (Shekhan)', 'ar' => 'أربيل (شيخان)'],
            // ['en' => 'Erbil (Shekh Isa)', 'ar' => 'أربيل (شيخ عيسى)'],
            // ['en' => 'Erbil (Saidkan)', 'ar' => 'أربيل (سيدكان)'],
            // ['en' => 'Erbil (Hiran)', 'ar' => 'أربيل (هيران)'],
            // ['en' => 'Erbil (Kani Yurd)', 'ar' => 'أربيل (كاني يرد)'],



            // ['en' => 'Najaf (Najaf)', 'ar' => 'النجف (النجف)'],
            // ['en' => 'Najaf (Kufa)', 'ar' => 'النجف (الكوفة)'],
            // ['en' => 'Najaf (Al-Manathera)', 'ar' => 'النجف (المناذرة)'],
            // ['en' => 'Najaf (Al-Hira)', 'ar' => 'النجف (الحيرة)'],
            // ['en' => 'Najaf (Al-Abbasiya)', 'ar' => 'النجف (العباسية)'],
            // ['en' => 'Najaf (Al-Mishkhab)', 'ar' => 'النجف (المشخاب)'],
            // ['en' => 'Najaf (Al-Qadisiyah Subdistrict)', 'ar' => 'النجف (ناحية القادسية)'],
            // ['en' => 'Najaf (Al-Hurriya)', 'ar' => 'النجف (الحرية)'],
            // ['en' => 'Najaf (Al-Haidariya)', 'ar' => 'النجف (الحيدرية)'],
            // ['en' => 'Najaf (Al-Shabaka Subdistrict)', 'ar' => 'النجف (ناحية الشبكة)'],
            // ['en' => 'Najaf (Al-Muhanawiya)', 'ar' => 'النجف (المهناوية)'],
            // ['en' => 'Najaf (Al-Rahba)', 'ar' => 'النجف (الرحبة)'],
            // ['en' => 'Najaf (Al-Radhawiya)', 'ar' => 'النجف (الرضوية)'],




            // ['en' => 'Dhi Qar (Nasiriyah)', 'ar' => 'ذي قار (قضاء الناصرية)'],
            // ['en' => 'Dhi Qar (Karma Bani Saeed)', 'ar' => 'ذي قار (قضاء كرمة بني سعيد)'],
            // ['en' => 'Dhi Qar (Al-Rifai)', 'ar' => 'ذي قار (قضاء الرفاعي)'],
            // ['en' => 'Dhi Qar (Souq Al-Shuyukh)', 'ar' => 'ذي قار (قضاء سوق الشيوخ)'],
            // ['en' => 'Dhi Qar (Al-Jabaish)', 'ar' => 'ذي قار (قضاء الجبايش)'],
            // ['en' => 'Dhi Qar (Al-Shatrah)', 'ar' => 'ذي قار (قضاء الشطرة)'],
            // ['en' => 'Dhi Qar (Al-Diwaniyah)', 'ar' => 'ذي قار (قضاء الدواية)'],
            // ['en' => 'Dhi Qar (Al-Fuhood)', 'ar' => 'ذي قار (قضاء الفهود)'],
            // ['en' => 'Dhi Qar (Al-Fajr)', 'ar' => 'ذي قار (قضاء الفجر)'],
            // ['en' => 'Dhi Qar (Maysaloon Subdistrict)', 'ar' => 'ذي قار (ناحية ميسلون)'],
            // ['en' => 'Dhi Qar (Al-Nasr)', 'ar' => 'ذي قار (قضاء النصر)'],
            // ['en' => 'Dhi Qar (Al-Gharraf)', 'ar' => 'ذي قار (قضاء الغراف)'],
            // ['en' => 'Dhi Qar (Al-Islah)', 'ar' => 'ذي قار (قضاء الإصلاح)'],
            // ['en' => 'Dhi Qar (Sayyid Dakhil)', 'ar' => 'ذي قار (قضاء سيد دخيل)'],
            // ['en' => 'Dhi Qar (Ur)', 'ar' => 'ذي قار (قضاء أور)'],
            // ['en' => 'Dhi Qar (Al-Batha)', 'ar' => 'ذي قار (قضاء البطحاء)'],
            // ['en' => 'Dhi Qar (Al-Hirzah Subdistrict)', 'ar' => 'ذي قار (ناحية الهرزة)'],
            // ['en' => 'Dhi Qar (Al-Akaikah Subdistrict)', 'ar' => 'ذي قار (ناحية العكيكة)'],
            // ['en' => 'Dhi Qar (Al-Fadhiliyah)', 'ar' => 'ذي قار (قضاء الفضلية)'],
            // ['en' => 'Dhi Qar (Al-Tar)', 'ar' => 'ذي قار (الطار)'],
            // ['en' => 'Dhi Qar (Al-Nasr)', 'ar' => 'ذي قار (قضاء النصر)'],
            // ['en' => 'Dhi Qar (Qalat Sukkar)', 'ar' => 'ذي قار (قلعة سكر)'],
            // ['en' => 'Dhi Qar (Al-Manar)', 'ar' => 'ذي قار (قضاء المنار)'],



            // ['en' => 'Kirkuk (Kirkuk)', 'ar' => 'كركوك (كركوك)'],
            // ['en' => 'Kirkuk (Taza Khurmatu)', 'ar' => 'كركوك (تازة خورماتو أو تازة)'],
            // ['en' => 'Kirkuk (Al-Multaqa)', 'ar' => 'كركوك (الملتقى)'],
            // ['en' => 'Kirkuk (Shwan)', 'ar' => 'كركوك (شوان)'],
            // ['en' => 'Kirkuk (Alton Kupri)', 'ar' => 'كركوك (التون كوبري)'],
            // ['en' => 'Kirkuk (Dibs)', 'ar' => 'كركوك (دبس)'],
            // ['en' => 'Kirkuk (Daquq)', 'ar' => 'كركوك (داقوق)'],
            // ['en' => 'Kirkuk (Laylan)', 'ar' => 'كركوك (ليلان)'],
            // ['en' => 'Kirkuk (Al-Hawija)', 'ar' => 'كركوك (الحويجة)'],
            // ['en' => 'Kirkuk (Al-Zab)', 'ar' => 'كركوك (الزاب)'],
            // ['en' => 'Kirkuk (Al-Riyadh)', 'ar' => 'كركوك (الرياض)'],
            // ['en' => 'Kirkuk (Al-Abbasi)', 'ar' => 'كركوك (العباسي)'],
            // ['en' => 'Kirkuk (Taq Taq)', 'ar' => 'كركوك (طق طق)'],
            // ['en' => 'Kirkuk (Al-Rashad)', 'ar' => 'كركوك (الرشاد)'],
            // ['en' => 'Kirkuk (Arsa)', 'ar' => 'كركوك (عرصة)'],
            // ['en' => 'Kirkuk (Al-Basil)', 'ar' => 'كركوك (البسل)'],





            // ['en' => 'Anbar (Ramadi)', 'ar' => 'الأنبار (الرمادي)'],
            // ['en' => 'Anbar (Fallujah)', 'ar' => 'الأنبار (الفلوجة)'],
            // ['en' => 'Anbar (Al-Qaim)', 'ar' => 'الأنبار (القائم)'],
            // ['en' => 'Anbar (Hit)', 'ar' => 'الأنبار (هيت)'],
            // ['en' => 'Anbar (Haditha)', 'ar' => 'الأنبار (حديثة)'],
            // ['en' => 'Anbar (Al-Rahaliya)', 'ar' => 'الأنبار (الرحالية)'],
            // ['en' => 'Anbar (Al-Habbaniya)', 'ar' => 'الأنبار (الحبانية)'],
            // ['en' => 'Anbar (Al-Khalidiya)', 'ar' => 'الأنبار (الخالدية)'],
            // ['en' => 'Anbar (Al-Walid)', 'ar' => 'الأنبار (الوليد)'],
            // ['en' => 'Anbar (Al-Sajariya)', 'ar' => 'الأنبار (الساجرية)'],
            // ['en' => 'Anbar (Al-Rutba)', 'ar' => 'الأنبار (الرطبة)'],
            // ['en' => 'Anbar (Akashat)', 'ar' => 'الأنبار (عكاشات)'],
            // ['en' => 'Anbar (Al-Baghdadi)', 'ar' => 'الأنبار (البغدادي)'],
            // ['en' => 'Anbar (Al-Karabla)', 'ar' => 'الأنبار (الكرابلة)'],
            // ['en' => 'Anbar (Kubaisa)', 'ar' => 'الأنبار (كبيسة)'],
            // ['en' => 'Anbar (Al-Nukhaib)', 'ar' => 'الأنبار (النخيب)'],
            // ['en' => 'Anbar (Al-Naimiya)', 'ar' => 'الأنبار (النعيمية)'],
            // ['en' => 'Anbar (Al-Sajr)', 'ar' => 'الأنبار (السجر)'],
            // ['en' => 'Anbar (Al-Rahaliya)', 'ar' => 'الأنبار (الرحالية)'],
            // ['en' => 'Anbar (Al-Saqra)', 'ar' => 'الأنبار (الصقرة)'],
            // ['en' => 'Anbar (Al-Jabha)', 'ar' => 'الأنبار (الجبه)'],
            // ['en' => 'Anbar (Al-Humayriyah)', 'ar' => 'الأنبار (الحميرية)'],
            // ['en' => 'Anbar (Al-Awsat)', 'ar' => 'الأنبار (الأوسط)'],
            // ['en' => 'Anbar (Al-Rumana)', 'ar' => 'الأنبار (الرمانة)'],
            // ['en' => 'Anbar (Al-Habariya)', 'ar' => 'الأنبار (الهبارية)'],
            // ['en' => 'Anbar (Al-Kasra)', 'ar' => 'الأنبار (الكسرة)'],
            // ['en' => 'Anbar (Al-Saqlawiya)', 'ar' => 'الأنبار (الصقلاوية)'],
            // ['en' => 'Anbar (Al-Ubaydi)', 'ar' => 'الأنبار (العبيدي)'],
            // ['en' => 'Anbar (Ana)', 'ar' => 'الأنبار (عانة)'],
            // ['en' => 'Anbar (Rawa)', 'ar' => 'الأنبار (راوة)'],
            // ['en' => 'Anbar (Al-Amiriya)', 'ar' => 'الأنبار (العامرية)'],
            // ['en' => 'Anbar (Barwana)', 'ar' => 'الأنبار (بروانة)'],
            // ['en' => 'Anbar (Al-Karma)', 'ar' => 'الأنبار (الكرمة)'],
            // ['en' => 'Anbar (Al-Haqlaniya)', 'ar' => 'الأنبار (الحقلانية)'],
            // ['en' => 'Anbar (Saada)', 'ar' => 'الأنبار (سعدة)'],
            // ['en' => 'Anbar (Al-Zawiya)', 'ar' => 'الأنبار (الزاوية)'],
            // ['en' => 'Anbar (Al-Rayhana)', 'ar' => 'الأنبار (الريحانة)'],
            // ['en' => 'Anbar (Al-Furat)', 'ar' => 'الأنبار (الفرات)'],
            // ['en' => 'Anbar (Al-Mohammadi)', 'ar' => 'الأنبار (المحمدي)'],
            // ['en' => 'Anbar (Husaybah East)', 'ar' => 'الأنبار (حصيبة الشرقية)'],
            // ['en' => 'Anbar (Al-Khayrat Subdistrict)', 'ar' => 'الأنبار (ناحية الخيرات)'],
            // ['en' => 'Anbar (Al-Dughaima)', 'ar' => 'الأنبار (الدغيمة)'],




            // ['en' => 'Diyala (Baqubah)', 'ar' => 'ديالى (بعقوبة)'],
            // ['en' => 'Diyala (Khanaqin)', 'ar' => 'ديالى (خانقين)'],
            // ['en' => 'Diyala (Jalawla)', 'ar' => 'ديالى (جلولاء)'],
            // ['en' => 'Diyala (Balad Ruz)', 'ar' => 'ديالى (بلدروز)'],
            // ['en' => 'Diyala (Kifri)', 'ar' => 'ديالى (كفري)'],
            // ['en' => 'Diyala (Al-Saadiya)', 'ar' => 'ديالى (السعدية قزربات)'],
            // ['en' => 'Diyala (Qara Tapa)', 'ar' => 'ديالى (قرة تبة)'],
            // ['en' => 'Diyala (Al-Azim)', 'ar' => 'ديالى (العظيم)'],
            // ['en' => 'Diyala (Al-Mansuriya)', 'ar' => 'ديالى (المنصورية)'],
            // ['en' => 'Diyala (Bahrz)', 'ar' => 'ديالى (بهرز)'],
            // ['en' => 'Diyala (Khan Bani Saad)', 'ar' => 'ديالى (خان بني سعد)'],
            // ['en' => 'Diyala (Al-Khalis)', 'ar' => 'ديالى (الخالص)'],
            // ['en' => 'Diyala (Mendeli)', 'ar' => 'ديالى (مندلي)'],
            // ['en' => 'Diyala (Tursaq)', 'ar' => 'ديالى (ترساق)'],
            // ['en' => 'Diyala (Naft Khana)', 'ar' => 'ديالى (نفط خانة)'],
            // ['en' => 'Diyala (Al-Miqdadiya)', 'ar' => 'ديالى (المقدادية)'],
            // ['en' => 'Diyala (Midan Subdistrict)', 'ar' => 'ديالى (ناحية ميدان)'],
            // ['en' => 'Diyala (Bamu Subdistrict)', 'ar' => 'ديالى (ناحية بمو)'],
            // ['en' => 'Diyala (Qurat Taw Subdistrict)', 'ar' => 'ديالى (ناحية قورة تو)'],
            // ['en' => 'Diyala (Al-Abara)', 'ar' => 'ديالى (العبارة)'],
            // ['en' => 'Diyala (Kan\'an)', 'ar' => 'ديالى (كنعان)'],
            // ['en' => 'Diyala (Al-Wihda)', 'ar' => 'ديالى (الوجيهية)'],
            // ['en' => 'Diyala (Hamrin Subdistrict)', 'ar' => 'ديالى (ناحية حمرين)'],
            // ['en' => 'Diyala (Qazaniya)', 'ar' => 'ديالى (قزانية)'],
            // ['en' => 'Diyala (Hebheb Subdistrict)', 'ar' => 'ديالى (ناحية هبهب)'],
            // ['en' => 'Diyala (Jadidat Al-Shatt Subdistrict)', 'ar' => 'ديالى (ناحية جديدة الشط)'],
            // ['en' => 'Diyala (Al-Azim Subdistrict)', 'ar' => 'ديالى (ناحية العظيم)'],
            // ['en' => 'Diyala (Al-Salam Subdistrict)', 'ar' => 'ديالى (ناحية السلام (30 تموز سابقا))'],
            // ['en' => 'Diyala (Awa Spi Subdistrict)', 'ar' => 'ديالى (ناحية ئاوة سبي)'],
            // ['en' => 'Diyala (Saraqa Subdistrict)', 'ar' => 'ديالى (ناحية سةرقة)'],
            // ['en' => 'Diyala (Nogol Subdistrict)', 'ar' => 'ديالى (ناحية نوجول)'],
            // ['en' => 'Diyala (Kurks Subdistrict)', 'ar' => 'ديالى (ناحية كوركس)'],
            // ['en' => 'Diyala (Sinkaw Subdistrict)', 'ar' => 'ديالى (ناحية سنكاو)'],
            // ['en' => 'Diyala (Takiya Subdistrict)', 'ar' => 'ديالى (ناحية تة كية)'],
            // ['en' => 'Diyala (Aghjalar Subdistrict)', 'ar' => 'ديالى (ناحية ئاغجة لةر)'],
            // ['en' => 'Diyala (Qadir Karam Subdistrict)', 'ar' => 'ديالى (ناحية قادر كرم)'],
            // ['en' => 'Diyala (Takiya Jabbari Subdistrict)', 'ar' => 'ديالى (ناحية تكية جباري)'],
            // ['en' => 'Diyala (Al-Hashimiya)', 'ar' => 'ديالى (الهاشمية)'],


            // ['en' => 'Muthanna (Samawah)', 'ar' => 'المثنى (السماوة)'],
            // ['en' => 'Muthanna (Al-Rumaitha)', 'ar' => 'المثنى (الرميثة)'],
            // ['en' => 'Muthanna (Al-Khidhir)', 'ar' => 'المثنى (الخضر)'],
            // ['en' => 'Muthanna (Al-Daraj)', 'ar' => 'المثنى (الدراجي)'],
            // ['en' => 'Muthanna (Al-Salman)', 'ar' => 'المثنى (السلمان)'],
            // ['en' => 'Muthanna (Al-Najmi District)', 'ar' => 'المثنى (قضاء النجمي)'],
            // ['en' => 'Muthanna (Al-Karama District)', 'ar' => 'المثنى (قضاء الكرامة)'],
            // ['en' => 'Muthanna (Basiya)', 'ar' => 'المثنى (بصية أو مخفر البصية)'],
            // ['en' => 'Muthanna (Al-Majd District)', 'ar' => 'المثنى (قضاء المجد)'],
            // ['en' => 'Muthanna (Al-Hilal District)', 'ar' => 'المثنى (قضاء الهلال)'],
            // ['en' => 'Muthanna (Al-Warka District)', 'ar' => 'المثنى (قضاء الوركاء)'],
            // ['en' => 'Muthanna (Al-Suwayr District)', 'ar' => 'المثنى (قضاء السوير)'],



            // ['en' => 'Qadisiyyah (Al-Diwaniyah)', 'ar' => 'القادسية (الديوانية)'],
            // ['en' => 'Qadisiyyah (Al-Shamiya District)', 'ar' => 'القادسية (قضاء الشامية)'],
            // ['en' => 'Qadisiyyah (Afak District)', 'ar' => 'القادسية (قضاء عفك)'],
            // ['en' => 'Qadisiyyah (Al-Sudair Subdistrict)', 'ar' => 'القادسية (ناحية السدير)'],
            // ['en' => 'Qadisiyyah (Al-Shoufa)', 'ar' => 'القادسية (الشوفه)'],
            // ['en' => 'Qadisiyyah (Al-Askari City)', 'ar' => 'القادسية (مدينة العسكري)'],
            // ['en' => 'Qadisiyyah (Al-Mursul)', 'ar' => 'القادسية (آل مرسول)'],
            // ['en' => 'Qadisiyyah (Al-Saniya District)', 'ar' => 'القادسية (قضاء السنية)'],
            // ['en' => 'Qadisiyyah (Al-Hamza District)', 'ar' => 'القادسية (قضاء الحمزة)'],
            // ['en' => 'Qadisiyyah (Al-Daghara Subdistrict)', 'ar' => 'القادسية (ناحية الدغارة)'],
            // ['en' => 'Qadisiyyah (Al-Shinafiyah)', 'ar' => 'القادسية (الشنافية)'],
            // ['en' => 'Qadisiyyah (Al-Salahiya)', 'ar' => 'القادسية (الصلاحية)'],
            // ['en' => 'Qadisiyyah (Ghamas)', 'ar' => 'القادسية (غماس)'],
            // ['en' => 'Qadisiyyah (Al-Budair District)', 'ar' => 'القادسية (قضاء البدير)'],
            // ['en' => 'Qadisiyyah (Imam Dhaher)', 'ar' => 'القادسية (إمام ظاهر)'],
            // ['en' => 'Qadisiyyah (Al-Mihnawiya District)', 'ar' => 'القادسية (قضاء المهناوية)'],
            // ['en' => 'Qadisiyyah (Akar Village)', 'ar' => 'القادسية (قرية عكر، تابعة للمهناوية)'],
            // ['en' => 'Qadisiyyah (Al-Khurnaq)', 'ar' => 'القادسية (الخورنق)'],
            // ['en' => 'Qadisiyyah (Al-Shafi\'iya)', 'ar' => 'القادسية (الشافعية)'],
            // ['en' => 'Qadisiyyah (Sumer District)', 'ar' => 'القادسية (قضاء سومر)'],
            // ['en' => 'Qadisiyyah (Qal\'at Abu Skhair)', 'ar' => 'القادسية (قلعة أبو صخير)'],




            // ['en' => 'Maysan (Amarah)', 'ar' => 'ميسان (العمارة)'],
            // ['en' => 'Maysan (Ali Al-Gharbi)', 'ar' => 'ميسان (علي الغربي)'],
            // ['en' => 'Maysan (Al-Maimouna)', 'ar' => 'ميسان (الميمونة)'],
            // ['en' => 'Maysan (Al-Majar Al-Kabir)', 'ar' => 'ميسان (المجر الكبير)'],
            // ['en' => 'Maysan (Qalat Saleh)', 'ar' => 'ميسان (قلعة صالح)'],
            // ['en' => 'Maysan (Al-Kahlaa)', 'ar' => 'ميسان (الكحلاء)'],
            // ['en' => 'Maysan (Ali Al-Sharqi)', 'ar' => 'ميسان (علي الشرقي)'],
            // ['en' => 'Maysan (Kumait)', 'ar' => 'ميسان (كميت)'],
            // ['en' => 'Maysan (Al-Mashrah)', 'ar' => 'ميسان (المشرح)'],
            // ['en' => 'Maysan (Al-Salam)', 'ar' => 'ميسان (السلام)'],
            // ['en' => 'Maysan (Al-Khair)', 'ar' => 'ميسان (الخير)'],
            // ['en' => 'Maysan (Al-Adl)', 'ar' => 'ميسان (العدل)'],
            // ['en' => 'Maysan (Bani Hashim)', 'ar' => 'ميسان (بني هاشم)'],
            // ['en' => 'Maysan (Al-Azair)', 'ar' => 'ميسان (العزير)'],
            // ['en' => 'Maysan (Ahmed Al-Rifai)', 'ar' => 'ميسان (أحمد الرفاعي)'],
            // ['en' => 'Maysan (Al-Shaib)', 'ar' => 'ميسان (الشيب)'],
            // ['en' => 'Maysan (Al-Tayib)', 'ar' => 'ميسان (الطيب)'],
            // ['en' => 'Maysan (Al-Rashidiya)', 'ar' => 'ميسان (الرشيدية)'],
            // ['en' => 'Maysan (Fayyadh)', 'ar' => 'ميسان (فياض)'],
            // ['en' => 'Maysan (Faris)', 'ar' => 'ميسان (فارس)'],
            // ['en' => 'Maysan (Al-Fakka)', 'ar' => 'ميسان (الفكه)'],
            // ['en' => 'Maysan (Al-Shalfa)', 'ar' => 'ميسان (الشلفه)'],
            // ['en' => 'Maysan (Al-Baydha)', 'ar' => 'ميسان (البيضة)'],
            // ['en' => 'Maysan (Abu Ghurab)', 'ar' => 'ميسان (أبو غراب)'],
            // ['en' => 'Maysan (Umm Obaida Subdistrict)', 'ar' => 'ميسان (ناحية أم عبيدة)'],




            // ['en' => 'Wasit (Al-Kut)', 'ar' => 'واسط (الكوت)'],
            // ['en' => 'Wasit (Al-Suwaira)', 'ar' => 'واسط (الصويرة)'],
            // ['en' => 'Wasit (Al-Aziziyah)', 'ar' => 'واسط (العزيزية)'],
            // ['en' => 'Wasit (Al-Zubaidiyah)', 'ar' => 'واسط (الزبيدية)'],
            // ['en' => 'Wasit (Al-Nu\'maniya)', 'ar' => 'واسط (النعمانية)'],
            // ['en' => 'Wasit (Sheikh Saad)', 'ar' => 'واسط (شيخ سعد)'],
            // ['en' => 'Wasit (Al-Hay)', 'ar' => 'واسط (الحي)'],
            // ['en' => 'Wasit (Badra)', 'ar' => 'واسط (بدرة)'],
            // ['en' => 'Wasit (Jassan)', 'ar' => 'واسط (جصان)'],
            // ['en' => 'Wasit (Al-Ahrar District)', 'ar' => 'واسط (قضاء الأحرار)'],
            // ['en' => 'Wasit (Taj Al-Din Subdistrict)', 'ar' => 'واسط (ناحية تاج الدين)'],
            // ['en' => 'Wasit (Mazra\'at Al-Suwaira)', 'ar' => 'واسط (مزرعة الصويرة)'],
            // ['en' => 'Wasit (Al-Dabouni)', 'ar' => 'واسط (الدبوني)'],





            // ['en' => 'Salah ad-Din (Tikrit)', 'ar' => 'صلاح الدين (تكريت)'],
            // ['en' => 'Salah ad-Din (Al-Awja)', 'ar' => 'صلاح الدين (العوجة)'],
            // ['en' => 'Salah ad-Din (Al-Alam District)', 'ar' => 'صلاح الدين (قضاء العلم)'],
            // ['en' => 'Salah ad-Din (Al-Dour)', 'ar' => 'صلاح الدين (الدور)'],
            // ['en' => 'Salah ad-Din (Samarra)', 'ar' => 'صلاح الدين (سامراء)'],
            // ['en' => 'Salah ad-Din (Mkeishifa)', 'ar' => 'صلاح الدين (مكيشيفة)'],
            // ['en' => 'Salah ad-Din (Al-Mu\'tasim)', 'ar' => 'صلاح الدين (المعتصم)'],
            // ['en' => 'Salah ad-Din (Baiji)', 'ar' => 'صلاح الدين (بيجي)'],
            // ['en' => 'Salah ad-Din (Al-Siniya)', 'ar' => 'صلاح الدين (الصينية)'],
            // ['en' => 'Salah ad-Din (Al-Shirqat)', 'ar' => 'صلاح الدين (الشرقاط)'],
            // ['en' => 'Salah ad-Din (Ashur Subdistrict)', 'ar' => 'صلاح الدين (ناحية اشور)'],
            // ['en' => 'Salah ad-Din (Al-Sahl Al-Akhdar Subdistrict)', 'ar' => 'صلاح الدين (ناحية السهل الاخضر)'],
            // ['en' => 'Salah ad-Din (Tulul Al-Baj Subdistrict)', 'ar' => 'صلاح الدين (ناحية تلول الباج)'],
            // ['en' => 'Salah ad-Din (Balad)', 'ar' => 'صلاح الدين (بلد)'],
            // ['en' => 'Salah ad-Din (Al-Dhuluiya)', 'ar' => 'صلاح الدين (الضلوعية)'],
            // ['en' => 'Salah ad-Din (Yathrib)', 'ar' => 'صلاح الدين (يثرب)'],
            // ['en' => 'Salah ad-Din (Aziz Balad)', 'ar' => 'صلاح الدين (عزيز بلد)'],
            // ['en' => 'Salah ad-Din (Al-Ishaqi Subdistrict)', 'ar' => 'صلاح الدين (ناحية الإسحاقي)'],
            // ['en' => 'Salah ad-Din (Al-Dujail)', 'ar' => 'صلاح الدين (الدجيل)'],
            // ['en' => 'Salah ad-Din (Tooz Khurmato)', 'ar' => 'صلاح الدين (طوز خورماتو)'],
            // ['en' => 'Salah ad-Din (Sulaiman Bek)', 'ar' => 'صلاح الدين (سليمان بيك)'],
            // ['en' => 'Salah ad-Din (Amerli)', 'ar' => 'صلاح الدين (آمرلي)'],
            // ['en' => 'Salah ad-Din (Yankjah)', 'ar' => 'صلاح الدين (ينكجة)'],
            // ['en' => 'Salah ad-Din (Ain Al-Dhab)', 'ar' => 'صلاح الدين (عين الدبس)'],
            // ['en' => 'Salah ad-Din (Halawiyan)', 'ar' => 'صلاح الدين (حليوان)'],
            // ['en' => 'Salah ad-Din (Sarevan)', 'ar' => 'صلاح الدين (سريفان)'],
            // ['en' => 'Salah ad-Din (Al-Dikani)', 'ar' => 'صلاح الدين (الديكاني)'],
            // ['en' => 'Salah ad-Din (Malha)', 'ar' => 'صلاح الدين (ملحة)'],
            // ['en' => 'Salah ad-Din (Al-Harmal)', 'ar' => 'صلاح الدين (الحرمل)'],
            // ['en' => 'Salah ad-Din (Al-Sharima)', 'ar' => 'صلاح الدين (الشريمة)'],
            // ['en' => 'Salah ad-Din (Abu Dalaf)', 'ar' => 'صلاح الدين (أبو دلف)'],
            // ['en' => 'Salah ad-Din (Al-Qalaa)', 'ar' => 'صلاح الدين (القلعة)'],
            // ['en' => 'Salah ad-Din (Al-Rikka)', 'ar' => 'صلاح الدين (الركة)'],
            // ['en' => 'Salah ad-Din (Al-Bu Atma)', 'ar' => 'صلاح الدين (البوطعمه)'],
            // ['en' => 'Salah ad-Din (Nawjul)', 'ar' => 'صلاح الدين (نوجل)'],
            // ['en' => 'Salah ad-Din (Imam Ibrahim Al-Sheikh)', 'ar' => 'صلاح الدين (إمام إبراهيم الشيخ)'],
            // ['en' => 'Salah ad-Din (Al-Sharia)', 'ar' => 'صلاح الدين (الشريعة)'],
            // ['en' => 'Salah ad-Din (Al-Mu\'tasim)', 'ar' => 'صلاح الدين (المعتصم)'],
            // ['en' => 'Salah ad-Din (Al-Bu Atma)', 'ar' => 'صلاح الدين (البوطعمه)'],





            // ['en' => 'Duhok (Duhok)', 'ar' => 'دهوك (دهوك)'],
            // ['en' => 'Duhok (Zakho)', 'ar' => 'دهوك (زاخو)'],
            // ['en' => 'Duhok (Darkar)', 'ar' => 'دهوك (دركار)'],
            // ['en' => 'Duhok (Akre)', 'ar' => 'دهوك (عقرة)'],
            // ['en' => 'Duhok (Zawita)', 'ar' => 'دهوك (زاويته)'],
            // ['en' => 'Duhok (Sarsang)', 'ar' => 'دهوك (سرسنك)'],
            // ['en' => 'Duhok (Amadiya)', 'ar' => 'دهوك (العمادية)'],
            // ['en' => 'Duhok (Sharanesh)', 'ar' => 'دهوك (شرانش)'],
            // ['en' => 'Duhok (Sumel)', 'ar' => 'دهوك (سميل)'],
            // ['en' => 'Duhok (Kani Masi)', 'ar' => 'دهوك (كاني ماسي)'],
            // ['en' => 'Duhok (Sulav)', 'ar' => 'دهوك (سولاف)'],
            // ['en' => 'Duhok (Batufa)', 'ar' => 'دهوك (باطوفا)'],
            // ['en' => 'Duhok (Fayda)', 'ar' => 'دهوك (فايدة)'],
            // ['en' => 'Duhok (Batil)', 'ar' => 'دهوك (باتيل)'],
            // ['en' => 'Duhok (Bamarni)', 'ar' => 'دهوك (بامرني)'],
            // ['en' => 'Duhok (Jamanki)', 'ar' => 'دهوك (جامانكي)'],
            // ['en' => 'Duhok (Mankishik)', 'ar' => 'دهوك (مانكيشك)'],
            // ['en' => 'Duhok (Hezawa)', 'ar' => 'دهوك (هيزاوا)'],




            // ['en' => 'Sulaymaniyah (Sulaymaniyah)', 'ar' => 'السليمانية (السليمانية)'],
            // ['en' => 'Sulaymaniyah (Bakrajo)', 'ar' => 'السليمانية (بكره جو)'],
            // ['en' => 'Sulaymaniyah (Bazyan)', 'ar' => 'السليمانية (بازيان)'],
            // ['en' => 'Sulaymaniyah (Tangaru)', 'ar' => 'السليمانية (تانجرو)'],
            // ['en' => 'Sulaymaniyah (Qaradagh District)', 'ar' => 'السليمانية (قضاء قره داغ)'],
            // ['en' => 'Sulaymaniyah (Sehsetan)', 'ar' => 'السليمانية (سيه سيتان)'],
            // ['en' => 'Sulaymaniyah (Sharazur)', 'ar' => 'السليمانية (شاره زور)'],
            // ['en' => 'Sulaymaniyah (Warmawa)', 'ar' => 'السليمانية (وارماوا)'],
            // ['en' => 'Sulaymaniyah (Sharaziz District)', 'ar' => 'السليمانية (قضاء شارباريز)'],
            // ['en' => 'Sulaymaniyah (Gwarta)', 'ar' => 'السليمانية (جوارتة)'],
            // ['en' => 'Sulaymaniyah (Sewtil)', 'ar' => 'السليمانية (سيوتيل)'],
            // ['en' => 'Sulaymaniyah (Sitak)', 'ar' => 'السليمانية (سيتك)'],
            // ['en' => 'Sulaymaniyah (Zelan)', 'ar' => 'السليمانية (زلان)'],
            // ['en' => 'Sulaymaniyah (Kapilon)', 'ar' => 'السليمانية (كابيلون)'],
            // ['en' => 'Sulaymaniyah (Mawat District)', 'ar' => 'السليمانية (قضاء ماوت)'],
            // ['en' => 'Sulaymaniyah (Pshdar District)', 'ar' => 'السليمانية (قضاء بشدر)'],
            // ['en' => 'Sulaymaniyah (Qalat Diza Subdistrict)', 'ar' => 'السليمانية (ناحية قلعة دزا)'],
            // ['en' => 'Sulaymaniyah (Hero Subdistrict)', 'ar' => 'السليمانية (ناحية هيرو)'],
            // ['en' => 'Sulaymaniyah (Halabja)', 'ar' => 'السليمانية (حلبجة)'],






            // محافظة بابل


            // ['en' => 'Babil (Hilla)', 'ar' => 'بابل (الحلة)'],
            // ['en' => 'Babil (Alexandria)', 'ar' => 'بابل (الإسكندرية)'],
            // ['en' => 'Babil (Al-Hashimiya District)', 'ar' => 'بابل (قضاء الهاشمية)'],
            // ['en' => 'Babil (Al-Haswa)', 'ar' => 'بابل (الحصوة)'],
            // ['en' => 'Babil (Al-Imam Subdistrict)', 'ar' => 'بابل (ناحية الإمام)'],
            // ['en' => 'Babil (Kutha District)', 'ar' => 'بابل (قضاء كوثى)'],
            // ['en' => 'Babil (Al-Kifl Subdistrict)', 'ar' => 'بابل (ناحية الكفل)'],
            // ['en' => 'Babil (Abu Gharaq Subdistrict)', 'ar' => 'بابل (ناحية أبي غرق)'],
            // ['en' => 'Babil (Al-Mahawil District)', 'ar' => 'بابل (قضاء المحاويل)'],
            // ['en' => 'Babil (Al-Nil Subdistrict)', 'ar' => 'بابل (ناحية النيل)'],
            // ['en' => 'Babil (Al-Qasim)', 'ar' => 'بابل (القاسم)'],
            // ['en' => 'Babil (Al-Talia Subdistrict)', 'ar' => 'بابل (ناحية الطليعة)'],
            // ['en' => 'Babil (Al-Musayab District)', 'ar' => 'بابل (قضاء المسيب)'],
            // ['en' => 'Babil (Saddat Al-Hindiyah Subdistrict)', 'ar' => 'بابل (ناحية سدة الهندية)'],
            // ['en' => 'Babil (Jurf Al-Nasr)', 'ar' => 'بابل (جرف النصر)'],

            // محافظة كربلاء


            // ['en' => 'Karbala (Sayyid Al-Awsiya City)', 'ar' => 'كربلاء (مدينة سيد الأوصياء)'],
            // ['en' => 'Karbala (Imam Al-Hussain City)', 'ar' => 'كربلاء (مدينة الإمام الحسين)'],
            // ['en' => 'Karbala (Imam Al-Hasan City)', 'ar' => 'كربلاء (مدينة الإمام الحسن)'],
            // ['en' => 'Karbala (Al-Abbas City)', 'ar' => 'كربلاء (مدينة العباس)'],
            // ['en' => 'Karbala (Durrat Karbala City)', 'ar' => 'كربلاء (مدينة درة كربلاء)'],
            // ['en' => 'Karbala (Al-Hurr Subdistrict)', 'ar' => 'كربلاء (ناحية الحر)'],
            // ['en' => 'Karbala (Al-Hussainiya)', 'ar' => 'كربلاء (الحسينية)'],
            // ['en' => 'Karbala (Ain Al-Tamr)', 'ar' => 'كربلاء (عين تمر)'],
            // ['en' => 'Karbala (Shathatha)', 'ar' => 'كربلاء (شثاثة)'],
            // ['en' => 'Karbala (Al-Hindiyah District)', 'ar' => 'كربلاء (قضاء الهندية)'],
            // ['en' => 'Karbala (Tweirij District)', 'ar' => 'كربلاء (قضاء طويريج)'],
            // ['en' => 'Karbala (Awn Subdistrict)', 'ar' => 'كربلاء (ناحية عون)'],
            // ['en' => 'Karbala (Al-Jadwal Al-Gharbi Subdistrict)', 'ar' => 'كربلاء (ناحية الجدول الغربي)'],
            // ['en' => 'Karbala (Al-Khayrat Subdistrict)', 'ar' => 'كربلاء (ناحية الخيرات)'],
            // ['en' => 'Karbala (Al-Razaza)', 'ar' => 'كربلاء (الرزازة)']
        ];

        foreach ($cities as $city) {
            City::create([
                'city_name' => $city,
            ]);
        }
    }
}
